name: shop_management
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # persistent_bottom_nav_bar: ^5.0.2
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0
  flutter_advanced_drawer: ^1.3.5
  # flutter_zoom_drawer: ^3.1.1
  provider: ^6.1.1
  animated_custom_dropdown: ^3.0.0
  floating_action_bubble: ^1.1.4
  animate_do: ^3.1.2
  another_flushbar: ^1.12.30
  intl: ^0.19.0
  flutter_native_splash: ^2.3.7
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  connectivity_plus: ^5.0.2
  flutter_easyloading: ^3.0.5
  cloud_firestore: ^4.14.0
  # fl_chart: ^0.66.0

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#111B21"
  image: assets/images/qasim.jpg
  image_dark: assets/images/qasim.jpg
  android_12:
    color: "#FFFFFF"
    color_dark: "#111B21"
    image: assets/images/qasim.jpg
    image_dark: assets/images/qasim.jpg
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#111B21"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
